name: FriCAS CI on Windows on CCL

on: workflow_dispatch
permissions: {}

jobs:
  build:

    runs-on: windows-2022
    timeout-minutes: 30
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        install: make mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp gmp-devel zip unzip

    - uses: actions/checkout@v4
    - name: configure and make
      run: |
        mkdir ../build && cd ../build
        wget https://github.com/Clozure/ccl/releases/download/v1.13/ccl-1.13-windowsx86.zip
        unzip ccl-1.13-windowsx86.zip
        ../jlfricas/configure --with-lisp=`pwd`/ccl/wx86cl64.exe --enable-gmp || cat config.log
        make -j4 --output-sync

    - name: Create artifact archives
      run: |
        cp -rp ../build/target/x86_64-w64-mingw32 jlFriCAS-windows-x86_64
        # rm jlFriCAS-windows-x86_64/bin/fricas
        cp /mingw64/bin/libgmp-10.dll jlFriCAS-windows-x86_64/lib/
        zip -r jlFriCAS-windows-CCL-x86_64-${{ github.sha }}.zip jlFriCAS-windows-x86_64

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: jlFriCAS-windows-CCL-x86_64-binary
        path: jlFriCAS-windows-CCL-x86_64-${{ github.sha }}.zip

    - name: make check
      run: cd ../build && make check -j4 --output-sync
